---
output:
  pdf_document:
    latex_engine: pdflatex
    template: ~/CV/td-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Anthony Damiano

jobtitle: "Postdoctoral Research Fellow, University of Minnesota"
address: "301 19th Ave S, Minneapolis, MN 55455"
fontawesome: yes
email: damia025@umn.edu
github: tdamiano
twitter: tony_damiano
#phone: "319-530-3532"
web: www.tonydamiano.com
#updated:

keywords: Urban planning, housing policy, R

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Education

*University	of	Minnesota*, PhD Public Affairs \hfill 2021

*University	of	Minnesota*, Master of Urban & Regional Planning  \hfill 2014

*Marquette University*, BA Political Science  \hfill 2010

# Teaching Experience

## University of Minnesota

*Instructor*

PA 5261 Housing Policy (2017, 2018, 2021)

*Teaching Assistant*

PA 5221 Private Sector Development (2015)


# Journal Articles
1. Goetz, E.G.,	R. Williams., __A. Damiano__. (2020). *Whiteness and Urban Planning*. Journal of the American Planning Association.


2. Lewis, B., Calhoun, M., Goetz, E.G.,  & __Damiano, A__. (2020). *Geographic Specificity Matters: Centering the Perspectives of Community Based Stakeholders for a Holistic Understanding of Gentrification in the Twin Cities*. City & Community.


3.  Goetz, E.G.,	__A. Damiano__ &	R. Williams. (2019). *Racially Concentrated Areas of Affluence: A Preliminary Investigation*. Cityscape: A Journal of Policy Development and Research, 21(1), 99–124.

Accompanying web site (https://tonydamiano.shinyapps.io/rcaa/)


# Research Publications
Goetz, E.G.,	__A. Damiano__, P. Brown, P. Alcorn, & J. Matson (2021) *Policy Implications of Rent Stabilization for Minneapolis, MN*. Prepared for the staff of the City of Minneapolis, MN.
[Link](https://www.cura.umn.edu/sites/cura.umn.edu/files/2021-08/Minneapolis-Rent-Stabilization-Study-web.pdf)

Goetz, E.G. & __A. Damiano__ (2019) *Gentrification in Suburban Hennepin County 2000-2016*. Prepared for the staff of Hennepin County, MN.

Goetz, E. G., Lewis, B., __Damiano, A.__, & Calhoun, M. (2019). *The Diversity of Gentrification: Multiple Forms of Gentrification in Minneapolis and St. Paul*. Retrieved from Center for Urban and Regional Affairs, University of Minnesota. [Link](http://gentrification.umn.edu/sites/gentrification.dl.umn.edu/files/media/diversity-of-gentrification-012519.pdf)


# Book Chapters
Goetz, E.G., __A. Damiano__ &	R. Williams. (2021). Changing the Narrative and Playbook on Racially Concentrated Areas of Poverty. In Joseph, M.L., & A.T. Khare (Eds.), *What Works to Promote Inclusive, Equitable Mixed‐Income Communities*. [Link](https://case.edu/socialwork/nimc/sites/case.edu.nimc/files/2020-09/Goetz.WWV_.Changing%20the%20Narrative.2020.pdf)

Goetz, E. G., Williams, R. A., & __Damiano, A.__ (2022). Whiteness and Urban Planning. In E. J. Mueller & J. R. Tighe (Eds.), *The Affordable Housing Reader* (2nd ed.). Routledge.


# Working Papers
__Damiano, A.__ & C. Frenier. (Updated Oct. 2020). "Build Baby Build?: Housing Submarkets and the Effects of
New Construction on Existing Rents. Center for Urban and Regional Affairs (CURA) Working Paper. [Link](https://www.tonydamiano.com/project/new-con/bbb-wp.pdf)


# Conference Papers
\* __Damiano, A.__ & C. Frenier.(2020) "Build Baby Build?: Housing Submarkets and the Effects of
New Construction on Existing Rents. Paper	presentation	at	the	Conference of the	American Collegiate	Schools	of Planning (ACSP) Annual Conference. Virtual.

\* __Damiano,	A__. (2019). *Whiteness and Planning*. Paper	presentation	at	the	Conference of the	American Collegiate	Schools	of Planning (ACSP) Annual Conference. Greenville, SC.

\*Goetz, E.G.,	R. Williams., & __A. Damiano__.(2019). *Whiteness and Planning*. Paper	presentation	at	the	Conference of the	American Collegiate	Schools	of	Planning (ACSP) Annual	Conference. Greenville, SC.

\*__Damiano,	A.__ 	(2019). *Effects of New Development on Existing Rents in Minneapolis, MN*. Paper presentation at the Urban	Affairs	Association Conference.	Los Angeles, CA.

\* __Damiano,	A__ (2017) *Beyond	Gentrification: Shifting	Neighborhood	Hierarchies	in	American Metropolitan	Areas.*	Paper	presentation at	the	Conference of the	American Collegiate	Schools	of	Planning (ACSP) Annual	Conference. Denver,	CO.

\*Lewis,	B.,	Goetz,	E.G.,	Calhoun,	M.,	__Damiano,	A.__ (2017) *Gentrification	Debates: Identifying Gentrification	and	its	Effects	in	Minneapolis-St.	Paul*. Paper presentation	at the	Conference of	the	American	Collegiate Schools of Planning (ACSP) Annual Conference.	Denver,	CO.

\*__Damiano.	A.__ &	E.G.	Goetz. (2017). *Is	the	Great	Inversion	Here	to	Stay?	:	New	Evidence &	Implications for	Public	Policy.* Paper presentation at	the	Urban	Affairs	Association Conference.	Minneapolis, MN.

Goetz,	E.G. &	\* __A.	Damiano.__	(2016).	*Exclusionism	or	Leveling?	Explaining	Rates	of	Affordable	Housing	Production	in	Suburban	Communities.*	Paper	presentation at	the	Annual	Conference	of	the	American	Collegiate	Schools	of	Planning (ACSP)	Annual Conference. Portland,	OR.

\*Goetz,	E.G.,	__A. Damiano__ &	J. Hicks.	(2015).	*On	Racially	Concentrated	Areas	of	Wealth.*	Paper	presentation at	the	Spatial	Foundations	of	Inequality	Conference sponsored	by the	Russell	Sage Foundation	NY,	NY.

_(\*Presenting Author)_

# Invited Talks
__Damiano,	A.__ & Molly Calhoun.	(2019, Oct). *Gentrification in Minneapolis & St. Paul*. Sustain St. Paul Monthly Meeting. St. Paul, MN.

__Damiano,	A.__ & Molly Calhoun.	(2019, Apr). *Gentrification in Minneapolis & St. Paul.* Twin Cities Habitat for Humanity Annual Board Meeting. St. Paul, MN.

__Damiano,	A.__ 	(2018, Sep). *Gentrification in Minneapolis & St. Paul: Quantitative Analysis.* National Association for County Community & Economic Development (NACCED). Minneapolis,	MN.

__Damiano,	A.__ & N. Mehta. (2016, Dec). *Gentrification in	Minneapolis.*	City of Minneapolis	Long-range Planning	Committee. Minneapolis,	MN.

__Damiano,	A.__ (2016,	Dec).	People’s	Assembly	on Gentrification. Parks	and	Power. Panel	Discussant.	Minneapolis, MN.

__Damiano,	A.__ (2016,	Sep).	*Gentrification: Who gets	to live	in Minneapolis in 2020?*.	Roundtable with Minneapolis City Counsel Member Alondra Cano.	Panel	Discussant.	Minneapolis, MN.

Goetz,	E.G. & __A.	Damiano__	(2016,	Nov).	*Gentrification	in	Minneapolis-St.Paul*.	Metropolitan Council	Staff	Meeting. St. Paul,	MN.

__Damiano, A.__ (2016,	Sep).	Beyond the Minnesota	Miracle – Suppressed Stories	&	Solutions. Institute for Advanced Study Thursday Roundtable.	Panel	Discussant.	Minneapolis,	MN.

__Damiano,	A.__ & J. Matson. (2016,	Sep).	*Gentrification	in	Minneapolis-St.	Paul:	A	Mixed-Methods	Approach.* Community Indicators Consortium	Annual Impact	Summit,	Washington	D.C.

__Damiano,	A.__, D. Davies, W. Johnson	&	D.	Porter.	(2014,	Oct).	*Bottineau Corridor Housing Needs	&	Affordability	Assessment.*	Minnesota	Chapter of the	American	Planning	Association	(APA)	Conference	Duluth,	MN.

__Damiano,	A.__ & J. Matson.	(2014,	Feb).	*Minneapolis-Saint Paul Housing Market Index: Monitoring Progress	after	the	Great	Recession.*	Federal	Reserve	Bank of Minneapolis	Community	Development	Conference,	Minneapolis,	MN.

__Damiano,	A.__ & J.	Matson.	(2014,	Oct).	*Asset Mapping	for	Community	Development.* University	of Minnesota	Annual Conference	on Policy	Analysis,	Saint	Paul,	MN.


# Awards
U-Spatial Mapping Prize _Best Interactive Map Graduate Student Category._ North Minneapolis Asset Project. 2013


# Professional Affiliations
Urban Affairs Association  (2014-Present)

American Collegiate Schools of Planning (2014-Present)

# Service
Reviewer:

City and Community, Urban Studies, Journal of the American Planning Association, Critical Sociology